import {tableColumnWeights,ResponsiveTableView} from './tableLayout'
import { Extension, Node, Mark, InputRule, mergeAttributes, type Extensions } from '@tiptap/core'
import { TableMap } from '@tiptap/pm/tables'
import { Plugin, TextSelection } from '@tiptap/pm/state'
import StarterKit from '@tiptap/starter-kit'
import { Table, TableCell, TableHeader, TableRow } from '@tiptap/extension-table'
import TaskList from '@tiptap/extension-task-list'
import TaskItem from '@tiptap/extension-task-item'
import Highlight from '@tiptap/extension-highlight'
import { pageFormat, accentValue, colors, icons, semanticItems, type FacetDocument } from '../core/model'
import defaultCover from '../assets/default-cover.svg?raw'
import { normalizeLink } from '../core/links'
import { pairedInput,pairTextarea } from './pairs'
import {documentSearch,searchKey} from './search'
import { tableResize } from './tableResize'
import { renderMath } from '../core/math'
export type RenderContext = { document: FacetDocument; outline: { id:string; text:string; level:number; page:number }[] }
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const highlightCode = (source: string, language: string) => {
  const keywords = /^(python|bash|javascript|typescript|json|latex)$/.test(language) ? /^(const|let|var|function|return|if|else|for|while|import|from|class|new|def|in|and|or|not|True|False|None|async|await|try|catch|throw|interface|type|extends|export|select|from|where|begin|end)$/ : /^$/
  const token = /("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|`(?:\\.|[^`\\])*`|\/\/[^\n]*|#[^\n]*|\b\d+(?:\.\d+)?\b|\b[A-Za-z_$][\w$]*\b)/g
  let out='', last=0, match:RegExpExecArray|null
  while((match=token.exec(source))){ out += esc(source.slice(last,match.index)); const raw=match[0]; const kind=/^(\/\/|#)/.test(raw)?'comment':/^["'`]/.test(raw)?'string':/^\d/.test(raw)?'number':keywords.test(raw)?'keyword':'name'; out += `<span class="tok-${kind}">${esc(raw)}</span>`; last=match.index+raw.length }
  return out+esc(source.slice(last))
}
const codeLines=(source:string,language:string,start=1,continues=false,query='')=>{
  const lines=source.split('\n');if(continues&&lines.at(-1)==='')lines.pop()
  const paint=(line:string)=>{if(!query)return highlightCode(line,language);let out='',last=0,at=0;while((at=line.toLowerCase().indexOf(query.toLowerCase(),last))>=0){out+=highlightCode(line.slice(last,at),language)+'<mark class="search-match">'+highlightCode(line.slice(at,at+query.length),language)+'</mark>';last=at+query.length}return out+highlightCode(line.slice(last),language)}
  return lines.map((line,index)=>`<span class="code-line" data-line="${index+start}">${paint(line)||'&#8203;'}</span>`).join('\n')
}
const attrs = (names: string[], defaults: Record<string,unknown> = {}) => Object.fromEntries(names.map(name=>[name,{default:defaults[name]??null,parseHTML:(e:HTMLElement)=>{const raw=e.getAttribute(`data-${name}`);if(raw===null)return defaults[name]??null;if(Array.isArray(defaults[name])){try{return JSON.parse(raw)}catch{return defaults[name]}}return typeof defaults[name]==='number'?Number(raw):typeof defaults[name]==='boolean'?raw==='true':raw},renderHTML:(a:Record<string,any>)=>a[name]!=null?{[`data-${name}`]:Array.isArray(a[name])?JSON.stringify(a[name]):a[name]}:{}}]))
export function extensions(context: () => RenderContext): Extensions {
  const identity = Extension.create({ name:'identity',addProseMirrorPlugins(){return [new Plugin({appendTransaction(transactions,_old,state){if(!transactions.some(t=>t.docChanged)||transactions.every(t=>t.getMeta('pagination')))return null;const tr=state.tr;state.doc.descendants((n,pos)=>{if(n.type.name!=='page'&&n.isBlock&&!n.attrs.id)tr.setNodeMarkup(pos,undefined,{...n.attrs,id:crypto.randomUUID()})});return tr.docChanged?tr.setMeta('identity',true):null}})]},addGlobalAttributes(){return [{types:['part','paragraph','heading','blockquote','bulletList','orderedList','listItem','taskList','taskItem','codeBlock','horizontalRule','callout','mathBlock','image','subfigure','columns','column','table','tableRow','tableCell','tableHeader','pageBreak','semanticList','semanticItem','documentTitle','tableOfContents'],attributes:{...attrs(['id','continuation','fragmentOffset','renderVersion']),layoutRepeat:{default:false,renderHTML:a=>a.layoutRepeat?{'data-layout-repeat':'true',contenteditable:'false'}:{}},id:{default:null,keepOnSplit:false,parseHTML:e=>e.getAttribute('data-id'),renderHTML:a=>a.id?{'data-id':a.id,id:`block-${a.id}`}:{}},continuation:{default:false,keepOnSplit:false,renderHTML:a=>a.continuation?{'data-continuation':'true'}:{}},fragmentOffset:{default:0,keepOnSplit:false,renderHTML:()=>({})},}}]} })
  const document = Node.create({name:'doc',topNode:true,content:'page+'})
  const page = Node.create({name:'page',content:'block+',isolating:false,addAttributes(){return {index:{default:1},total:{default:1},isCover:{default:false},layoutKey:{default:''}}},parseHTML(){return [{tag:'section.facet-page'}]},renderHTML({node}){
    const d=context().document,format=pageFormat(d.page)
    return ['section',{class:'facet-page','data-page':node.attrs.index,'data-orientation':d.page.orientation||'portrait',style:`--page-margin:${d.page.margin}mm;--page-width:${format.width}mm;--page-height:${format.height}mm;--content-height:${format.height-d.page.margin*2}mm`},
      ['div',{class:`page-header ${node.attrs.isCover?'cover-hidden':''}`,contenteditable:'false'},d.page.header],
      ['div',{class:'page-content'},0],['div',{class:`page-footer ${node.attrs.isCover?'cover-hidden':''}`,contenteditable:'false'},['span',{},d.page.footer],['span',{},node.attrs.isCover?'':`${Math.max(1,node.attrs.index-(d.content[0]?.type==='documentTitle'?1:0))} / ${Math.max(1,node.attrs.total-(d.content[0]?.type==='documentTitle'?1:0))}`]]]
  }})
  const callout = Node.create({name:'callout',group:'block',content:'(paragraph | bulletList | orderedList | taskList | semanticList | mathBlock)+',defining:true,addAttributes(){return attrs(['variant','title','icon','color'],{variant:'info',title:'信息',icon:'info-circle',color:'darkblue'})},parseHTML(){return [{tag:'aside[data-variant]'}]},renderHTML({node,HTMLAttributes}){
    const icon=icons.includes(node.attrs.icon)?node.attrs.icon:'info-circle'
    return ['aside',mergeAttributes(HTMLAttributes,{class:'callout',style:`--callout-color:${accentValue(node.attrs.color)}`}),
      ['div',{class:'callout-title',contenteditable:'false','data-edit-card':'true'},['i',{class:`fas fa-${icon}`}],['span',{},node.attrs.title||'']],['div',{class:'callout-body'},0]]
  }})
  const math = (inline:boolean)=>Node.create({name:inline?'mathInline':'mathBlock',group:inline?'inline':'block',inline,atom:true,selectable:true,addInputRules(){return [new InputRule({find:inline?/(?:^|[^\\$])(\$([^$\n]+)\$)$/:/^\$\$([\s\S]+?)\$\$$/,handler:({state,range,match})=>{const latex=inline?match[2]:match[1];if(!latex.trim())return null;const node=this.type.create({latex:latex.trim()});if(inline){state.tr.replaceWith(range.from+match[0].length-match[1].length,range.to,node)}else{const $pos=state.doc.resolve(range.from);state.tr.replaceWith($pos.before(),$pos.after(),node)} }})]},addAttributes(){return attrs(['latex'],{latex:''})},parseHTML(){return [{tag:inline?'span[data-math]':'div[data-math]'}]},renderHTML({node,HTMLAttributes}){
    const dom=documentGlobal.createElement(inline?'span':'div'); Object.entries(HTMLAttributes).forEach(([k,v])=>dom.setAttribute(k,String(v)))
    dom.className=inline?'math-inline':'math-block';dom.dataset.math='true';dom.contentEditable='false'
    try{dom.innerHTML=renderMath(node.attrs.latex,!inline)}catch(e){dom.classList.add('invalid-math');dom.textContent=`公式待修复：${node.attrs.latex}`;dom.dataset.error=String(e)}
    return dom
  }})
  const image = Node.create({name:'image',group:'block',atom:true,draggable:true,addAttributes(){return attrs(['src','assetId','caption','width'],{src:'',assetId:'',caption:'',width:100})},parseHTML(){return [{tag:'figure[data-assetId]'}]},renderHTML({node,HTMLAttributes}){return ['figure',mergeAttributes(HTMLAttributes,{class:'image-block',style:`width:${Math.max(10,Math.min(100,Number(node.attrs.width)))}%`}),['img',{src:node.attrs.src,alt:node.attrs.caption||'文档图片',draggable:'false'}],['figcaption',{},node.attrs.caption||'']]}})
  const part=Node.create({name:'part',group:'block',content:'inline*',defining:true,parseHTML(){return [{tag:'h1[data-part]'}]},renderHTML({HTMLAttributes}){return ['h1',mergeAttributes(HTMLAttributes,{'data-part':'true',class:'document-part'}),0]},addKeyboardShortcuts(){return {Enter:()=>this.editor.isActive('part')?this.editor.commands.command(({tr,state,dispatch})=>{const at=state.selection.$from.after();tr.insert(at,state.schema.nodes.paragraph.create());tr.setSelection(TextSelection.create(tr.doc,at+1));if(dispatch)dispatch(tr);return true}):false}}})
  const pageBreak=Node.create({name:'pageBreak',group:'block',atom:true,selectable:true,parseHTML(){return [{tag:'div[data-page-break]'}]},renderHTML({HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{'data-page-break':'true',class:'manual-page-break',contenteditable:'false'}),['span',{},'分页符']]}})
  const badge=Node.create({name:'badge',group:'inline',inline:true,atom:true,addAttributes(){return attrs(['text','color'],{text:'进行中',color:'darkblue'})},parseHTML(){return [{tag:'span[data-badge]'}]},renderHTML({node,HTMLAttributes}){return ['span',mergeAttributes(HTMLAttributes,{'data-badge':'true',class:'badge',style:`--badge-color:${accentValue(node.attrs.color)}`}),node.attrs.text]}})
  const icon=Node.create({name:'inlineIcon',group:'inline',inline:true,atom:true,addAttributes(){return attrs(['icon','color'],{icon:'star',color:'darkblue'})},parseHTML(){return [{tag:'i[data-inline-icon]'}]},renderHTML({node,HTMLAttributes}){return ['i',mergeAttributes(HTMLAttributes,{'data-inline-icon':'true',class:`inline-icon fas fa-${icons.includes(node.attrs.icon)?node.attrs.icon:'star'}`,style:`color:${accentValue(node.attrs.color)}`})]}})
  const semanticList=Node.create({name:'semanticList',group:'block',content:'semanticItem+',parseHTML(){return [{tag:'ul.semantic-list'}]},renderHTML({HTMLAttributes}){return ['ul',mergeAttributes(HTMLAttributes,{class:'semantic-list'}),0]}})
  const semanticItem=Node.create({name:'semanticItem',content:'paragraph+',defining:true,addAttributes(){return attrs(['kind'],{kind:'good'})},parseHTML(){return [{tag:'li[data-kind]'}]},renderHTML({node,HTMLAttributes}){const s=semanticItems.find(x=>x.key===node.attrs.kind)??semanticItems[0];return ['li',mergeAttributes(HTMLAttributes,{style:`--item-color:${colors[s.color]}`}),['i',{class:`fas fa-${s.icon}`,contenteditable:'false'}],['div',{},0]]},addKeyboardShortcuts(){return {Enter:()=>this.editor.commands.splitListItem('semanticItem'),Tab:()=>false}}})
  const semanticStyle=Mark.create({name:'semanticStyle',addAttributes(){return attrs(['kind'],{kind:'important'})},parseHTML(){return [{tag:'span[data-semantic]'}]},renderHTML({HTMLAttributes}){return ['span',mergeAttributes(HTMLAttributes,{'data-semantic':'true',class:`style-${HTMLAttributes['data-kind']}`}),0]}})
  const title=Node.create({name:'documentTitle',group:'block',atom:true,parseHTML(){return [{tag:'header.document-title'}]},renderHTML({node,HTMLAttributes}){const d=context().document,m=d.metadata,a=m.coverAssetId?d.assets[m.coverAssetId]:undefined,url=normalizeLink(m.authorUrl||'');const byline=[m.author&&(url?['a',{href:url,target:'_blank',rel:'noreferrer'},m.author]:m.author),m.institute,m.date].filter(Boolean).map(x=>Array.isArray(x)?x:String(x)).reduce((acc:any[],x:any)=>acc.concat(acc.length?['  ·  ',x]:[x]),[]);return ['header',mergeAttributes(HTMLAttributes,{class:`document-title ${node.attrs.cover!==false?'cover-title':''}`,contenteditable:'false'}),...(a?[['img',{class:'cover-image',src:`data:${a.mime};base64,${a.data}`,alt:''}]]:[]),['div',{class:'document-eyebrow'},'FACET / RESEARCH NOTE'],['h1',{},m.title||'未命名文档'],...(m.subtitle?[['p',{class:'subtitle'},m.subtitle] as any]:[]),['div',{class:'document-byline'},...byline],...(!a?[['img',{class:'default-cover-image',src:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(defaultCover)}`,alt:'层叠山峦与日光的研究笔记封面插画'}]]:[]) ]}})
  const toc=Node.create({name:'tableOfContents',group:'block',atom:true,parseHTML(){return [{tag:'nav.document-toc'}]},renderHTML({HTMLAttributes}){return ['nav',mergeAttributes(HTMLAttributes,{class:'document-toc',contenteditable:'false'}),['div',{class:'toc-kicker'},'CONTENTS'],['h2',{},'目录'],...context().outline.filter(x=>x.level<=(context().document.page.tocDepth??3)).map(x=>['a',{class:`toc-line toc-level-${x.level}`,href:`#block-${x.id}`,'data-toc-target':x.id},['span',{class:'toc-label'},x.text],['span',{class:'toc-leader','aria-hidden':'true'}],['span',{class:'toc-page'},String(Math.max(1,x.page-(context().document.content[0]?.type==='documentTitle'?1:0)))]] as any)]}})
  const codeBlock=Node.create({
    name:'codeBlock',group:'block',content:'text*',code:true,defining:true,
    addAttributes(){return attrs(['language','codeLineStart','codeContinues'],{language:'text',codeLineStart:1,codeContinues:false})},
    parseHTML(){return [{tag:'div.code-editor-node',contentElement:'pre code'},{tag:'pre'}]},
    renderHTML({node,HTMLAttributes}){const dom=documentGlobal.createElement('div');Object.entries(HTMLAttributes).forEach(([key,value])=>dom.setAttribute(key,String(value)));dom.className='code-editor-node';dom.dataset.language=node.attrs.language||'text';dom.innerHTML=`<div class="code-language-bar">${esc(node.attrs.language||'text')}</div><pre class="code-block language-${esc(node.attrs.language||'text')}"><code>${codeLines(node.textContent,node.attrs.language||'text',Number(node.attrs.codeLineStart)||1,node.attrs.codeContinues)}</code></pre>`;return dom},
    addNodeView(){return ({node,getPos,editor})=>{
      const dom=documentGlobal.createElement('div'),bar=documentGlobal.createElement('div'),select=documentGlobal.createElement('select'),pre=documentGlobal.createElement('pre'),code=documentGlobal.createElement('code'),area=documentGlobal.createElement('textarea')
      dom.className='code-editor-node';bar.className='code-language-bar';bar.contentEditable='false';select.setAttribute('aria-label','代码语言')
      for(const language of ['text','python','bash','latex','javascript','typescript','json','html','css','sql','java','c','cpp','rust','go']){const option=documentGlobal.createElement('option');option.value=language;option.textContent=language==='text'?'纯文本':language;select.append(option)}
      bar.append(select);area.setAttribute('aria-label','代码编辑区');area.spellcheck=false;dom.append(bar,pre,area)
      const sync=(value:string,language:string)=>{dom.dataset.id=node.attrs.id;dom.dataset.language=language||'text';select.value=language||'text';pre.className=`code-block language-${language||'text'}`;code.className=`language-${language||'text'}`;code.innerHTML=codeLines(value,language||'text',Number(node.attrs.codeLineStart)||1,node.attrs.codeContinues,searchKey.getState(editor.state)?.query||'');pre.replaceChildren(code);if(area.value!==value)area.value=value}
      sync(node.textContent,node.attrs.language)
      select.addEventListener('change',()=>{const pos=getPos();if(typeof pos==='number')editor.view.dispatch(editor.state.tr.setNodeMarkup(pos,undefined,{...node.attrs,language:select.value}))})
      area.addEventListener('keydown',event=>pairTextarea(event,area))
      area.addEventListener('input',()=>{const pos=getPos();if(typeof pos!=='number')return;const text=area.value,from=pos+1,to=from+node.content.size;editor.view.dispatch(editor.state.tr.replaceWith(from,to,text?editor.schema.text(text):[]))})
      return {dom,update(updated:any){if(updated.type.name!=='codeBlock')return false;node=updated;sync(updated.textContent,updated.attrs.language);return true},stopEvent:(event:any)=>event.target===area||bar.contains(event.target),ignoreMutation:()=>true}
    }}
  })
  const subfigure=Node.create({name:'subfigure',group:'block',atom:true,selectable:true,addAttributes(){return attrs(['items','columns','width','gap'],{items:[],columns:2,width:100,gap:12})},parseHTML(){return [{tag:'figure.subfigure'}]},renderHTML({node,HTMLAttributes}){const items=Array.isArray(node.attrs.items)?node.attrs.items:[];const grid=documentGlobal.createElement('figure');Object.entries(mergeAttributes(HTMLAttributes,{class:'subfigure',style:`width:${Math.max(20,Math.min(100,Number(node.attrs.width)||100))}%;--subfigure-columns:${Math.max(1,Math.min(4,Number(node.attrs.columns)||2))};--subfigure-gap:${Number(node.attrs.gap??12)}px`})).forEach(([k,v])=>grid.setAttribute(k,String(v)));items.forEach((item:any,index:number)=>{const cell=documentGlobal.createElement('div');cell.className='subfigure-cell';const img=documentGlobal.createElement('img');img.src=item.src||'';img.alt=item.caption||`子图 ${String.fromCharCode(97+index)}`;cell.append(img);const cap=documentGlobal.createElement('figcaption');cap.textContent=item.caption||`(${String.fromCharCode(97+index)})`;cell.append(cap);grid.append(cell)});return grid}})
  const columns=Node.create({name:'columns',group:'block',content:'column column',defining:true,isolating:true,addAttributes(){return attrs(['ratio','gap'],{ratio:50,gap:24})},parseHTML(){return [{tag:'div.two-columns'}]},renderHTML({node,HTMLAttributes}){const ratio=Math.max(20,Math.min(80,Number(node.attrs.ratio)||50));return ['div',mergeAttributes(HTMLAttributes,{class:'two-columns',style:`grid-template-columns:minmax(0,${ratio}fr) minmax(0,${100-ratio}fr);gap:${Number(node.attrs.gap??24)}px`}),0]},addNodeView(){return ({node,getPos,editor})=>{
    const dom=documentGlobal.createElement('div'),content=documentGlobal.createElement('div'),handle=documentGlobal.createElement('div')
    dom.className='columns-editor';content.className='two-columns';handle.className='column-resizer';handle.contentEditable='false';handle.tabIndex=0;handle.setAttribute('role','separator');handle.setAttribute('aria-label','拖动调整双栏宽度');handle.setAttribute('aria-orientation','vertical');handle.setAttribute('aria-valuemin','20');handle.setAttribute('aria-valuemax','80');handle.title='拖动调整左右栏宽度；按方向键微调。双击双栏可调整栏间距。';dom.append(content,handle)
    const sync=()=>{const ratio=Number(node.attrs.ratio)||50,gap=Number(node.attrs.gap??24);content.dataset.ratio=String(ratio);content.dataset.id=node.attrs.id;content.style.gridTemplateColumns=`minmax(0,${ratio}fr) minmax(0,${100-ratio}fr)`;content.style.gap=`${gap}px`;handle.style.left=`calc((100% - ${gap}px) * ${ratio/100} + ${gap/2}px)`;handle.setAttribute('aria-valuenow',String(ratio))};sync()
    const commit=(ratio:number)=>{const pos=getPos();if(typeof pos==='number')editor.view.dispatch(editor.state.tr.setNodeMarkup(pos,undefined,{...node.attrs,ratio:Math.max(20,Math.min(80,Math.round(ratio)))}))}
    handle.addEventListener('pointerdown',event=>{event.preventDefault();handle.setPointerCapture(event.pointerId)})
    handle.addEventListener('pointermove',event=>{if(!handle.hasPointerCapture(event.pointerId))return;const rect=content.getBoundingClientRect(),scale=rect.width/content.offsetWidth,gap=Number(node.attrs.gap??24)*scale;const ratio=Math.max(20,Math.min(80,100*(event.clientX-rect.left-gap/2)/(rect.width-gap)));handle.dataset.pending=String(ratio);content.style.gridTemplateColumns=`minmax(0,${ratio}fr) minmax(0,${100-ratio}fr)`;handle.style.left=`${event.clientX-rect.left}px`})
    handle.addEventListener('pointerup',event=>{if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);if(handle.dataset.pending){commit(Number(handle.dataset.pending));delete handle.dataset.pending}})
    handle.addEventListener('pointercancel',()=>{delete handle.dataset.pending;sync()})
    handle.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();commit(Number(node.attrs.ratio)+(event.key==='ArrowLeft'?-1:1))}})
    return {dom,contentDOM:content,update(updated:any){if(updated.type.name!=='columns')return false;node=updated;sync();return true},stopEvent:event=>handle.contains(event.target as globalThis.Node),ignoreMutation:mutation=>mutation.type!=='selection'&&(mutation.target===handle||mutation.target===content&&mutation.type==='attributes')}
  }}})
  const column=Node.create({name:'column',content:'(paragraph | heading | bulletList | orderedList | taskList | blockquote | callout | mathBlock | image | subfigure | codeBlock | table | semanticList | horizontalRule)+',defining:true,isolating:true,parseHTML(){return [{tag:'div.column-content'}]},renderHTML({HTMLAttributes}){return ['div',mergeAttributes(HTMLAttributes,{class:'column-content'}),0]}})
  const styledTable=Table.extend({renderHTML({node,HTMLAttributes}){const weights=tableColumnWeights(node),sum=weights.reduce((a,b)=>a+b,0);return ['table',mergeAttributes(HTMLAttributes,{style:'width:100%;min-width:0;table-layout:fixed'}),['colgroup',{},...weights.map(w=>['col',{style:'width:'+w/sum*100+'%'}])],['tbody',0]] as any},addAttributes(){return {...this.parent?.(),tableStyle:{default:'academic',parseHTML:element=>element.getAttribute('data-table-style')||'academic',renderHTML:attributes=>({'data-table-style':attributes.tableStyle})}}}})
  const cellAlignment=Extension.create({name:'cellAlignment',addProseMirrorPlugins(){return [new Plugin({appendTransaction(transactions,_old,state){
    if(!transactions.some(t=>t.docChanged)||transactions.every(t=>t.getMeta('pagination')))return null
    const tr=state.tr,alignments=new Map<string,string[]>()
    state.doc.descendants((table,pos)=>{if(table.type.name!=='table')return;const map=TableMap.get(table);let columns=alignments.get(table.attrs.id);if(!columns){columns=Array.from({length:map.width},(_,col)=>table.nodeAt(map.map[col])?.attrs.textAlign||'left');alignments.set(table.attrs.id,columns)}const seen=new Set<number>();for(let row=0;row<map.height;row++)for(let col=0;col<map.width;col++){const offset=map.map[row*map.width+col];if(seen.has(offset))continue;seen.add(offset);const cell=table.nodeAt(offset),textAlign=columns[col]||'left';if(cell&&cell.attrs.textAlign!==textAlign)tr.setNodeMarkup(pos+1+offset,undefined,{...cell.attrs,textAlign})}return false})
    return tr.docChanged?tr:null
  }})]},addGlobalAttributes(){return [{types:['tableCell','tableHeader'],attributes:{textAlign:{default:'left',parseHTML:e=>e.style.textAlign||'left',renderHTML:a=>({style:`text-align:${['left','center','right'].includes(a.textAlign)?a.textAlign:'left'}`})}}}]}})
  const quoteColor=Extension.create({name:'quoteColor',addGlobalAttributes(){return [{types:['blockquote'],attributes:{color:{default:'darkblue',parseHTML:e=>e.getAttribute('data-color')||'darkblue',renderHTML:a=>({'data-color':a.color,style:`--quote-color:${accentValue(a.color)}`})}}}]}})
  const headingAttributes=Extension.create({name:'headingAttributes',addGlobalAttributes(){return [{types:['heading'],attributes:attrs(['icon','numbered','toc','number'],{icon:'',numbered:false,toc:true,number:''})}]}})
  const heading=Node.create({name:'heading',group:'block',content:'inline*',defining:true,addAttributes(){return {level:{default:1},...attrs(['icon','numbered','toc','number'],{icon:'',numbered:false,toc:true,number:''})}},parseHTML(){return [1,2,3].map(level=>({tag:`h${level}`,attrs:{level}}))},renderHTML({node,HTMLAttributes}){return [`h${Math.min(3,Math.max(1,node.attrs.level))}`,mergeAttributes(HTMLAttributes),...(node.attrs.icon?[['i',{class:`heading-icon fas fa-${icons.includes(node.attrs.icon)?node.attrs.icon:'book'}`,contenteditable:'false'}] as any]:[]),['span',{},0]]}})
  return [document,page,identity,pairedInput,documentSearch,quoteColor,tableResize,heading,codeBlock,subfigure,columns,column,cellAlignment,StarterKit.configure({document:false,heading:false,codeBlock:false,link:{openOnClick:false,defaultProtocol:'https',protocols:['http','https','mailto','tel'],HTMLAttributes:{title:'按住 Ctrl / ⌘ 点击打开链接'}}}),part,styledTable.configure({resizable:false,View:ResponsiveTableView}),TableRow,TableHeader,TableCell,TaskList,TaskItem.configure({nested:false,HTMLAttributes:{'data-type':'taskItem'}}),Highlight,callout,math(false),math(true),image,pageBreak,badge,icon,semanticList,semanticItem,semanticStyle,title,toc,headingAttributes]
}
const documentGlobal=globalThis.document
export { esc }
