import {test,expect} from '@playwright/test'
const office='<html><body><!--StartFragment--><table width="2400" style="width:1800pt"><colgroup><col width="120"><col width="1120"><col width="220"><col width="940"></colgroup><tbody><tr><th>序号</th><th>名称</th><th>年份</th><th>简记</th></tr><tr><td>1</td><td><p><b>Research overview</b></p><p>Second paragraph</p></td><td>2026</td><td>完整内容</td></tr><tr><td rowspan="2">2</td><td colspan="2">Merged cells</td><td>NOTE</td></tr><tr><td>Last</td><td></td><td></td></tr><tr><td></td><td></td><td></td><td></td></tr></tbody></table><!--EndFragment--></body></html>'
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('facet-guide-seen','true'));await page.goto('/');await page.waitForFunction(()=>window.__facet?.editor);await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph'}];f.load(d)});await page.locator('.tiptap p').click()})
async function fits(page:any){expect(await page.locator('.tiptap table').evaluateAll((ts:any[])=>ts.every(t=>t.getBoundingClientRect().right<=t.closest('.page-content').getBoundingClientRect().right+1))).toBe(true)}
test('Office HTML wins over clipboard preview and preserves merged and empty cells',async({page})=>{
 await page.evaluate(html=>{const data=new DataTransfer();data.setData('text/html',html);data.setData('text/plain','preview');data.items.add(new File(['preview'],'preview.png',{type:'image/png'}));window.__facet.editor.view.dom.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))},office)
 await expect(page.locator('.tiptap table')).toHaveCount(1);await expect(page.locator('.tiptap table tr')).toHaveCount(5);await expect(page.locator('.tiptap table td[rowspan="2"]')).toHaveText('2');await expect(page.locator('.tiptap table td[colspan="2"]')).toHaveText('Merged cells');await expect(page.locator('.tiptap table strong')).toHaveText('Research overview');await expect(page.locator('.tiptap table')).toContainText('完整内容');await fits(page)
 await page.screenshot({path:'test-results/office-table-fit.png'})
 const widths=await page.locator('.tiptap col').evaluateAll(cs=>cs.map(c=>c.getBoundingClientRect().width));expect(widths[1]/widths[0]).toBeCloseTo(1120/120,0)
 await page.evaluate(()=>{const f=window.__facet;f.paginate()});await fits(page)
 const html=await page.evaluate(()=>window.__facet.exportHTML());await page.setContent(html);expect(await page.locator('table').evaluate(t=>t.getBoundingClientRect().width<=t.closest('.page-content')!.getBoundingClientRect().width+1)).toBe(true)
})
test('existing oversized tables adapt to portrait, landscape and Beamer without changing cell text',async({page})=>{
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'table',content:[{type:'tableRow',content:[2000,500,800].map((w,i)=>({type:'tableCell',attrs:{colwidth:[w]},content:[{type:'paragraph',content:[{type:'text',text:'Column '+i}]}]}))}]}];f.load(d)});await fits(page)
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.page.orientation='landscape';f.load(d)});await fits(page)
 const result=await page.evaluate(()=>window.__facet.exportBeamer());await page.setContent(result.html);expect(await page.locator('table').evaluate(t=>t.getBoundingClientRect().width<=t.closest('.beamer-content')!.getBoundingClientRect().width+1)).toBe(true);await expect(page.locator('table')).toContainText('Column 2')
})
test('right-click preserves table structure and plain text keeps literal dollars and tabs',async({page})=>{
 await page.evaluate(html=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{read:async()=>[{types:['text/html','text/plain','image/png'],getType:async(t:string)=>new Blob([t==='text/html'?html:'A\t$B$\n1\t2'],{type:t})}],readText:async()=>'A\t$B$\n1\t2'}}),office)
 await page.locator('.tiptap p').click({button:'right'});await page.getByRole('menuitem',{name:'粘贴并匹配当前样式'}).click();await expect(page.locator('.tiptap table')).toHaveCount(1);await fits(page)
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph'}];f.load(d)});await page.locator('.tiptap p').click({button:'right'});await page.getByRole('menuitem',{name:'粘贴为纯文本'}).click();await expect(page.locator('.tiptap table')).toHaveCount(0);await expect(page.locator('.tiptap .math-inline')).toHaveCount(0);await expect(page.locator('.tiptap')).toContainText('$B$')
})
test('tab separated clipboard text becomes an editable table',async({page})=>{
 await page.evaluate(()=>{const data=new DataTransfer();data.setData('text/plain','Name\tYear\tNotes\r\nAlpha\t2026\t\r\nBeta\t2025\tLast');window.__facet.editor.view.dom.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))});await expect(page.locator('.tiptap table tr')).toHaveCount(3);await expect(page.locator('.tiptap table tr').nth(1).locator('td').nth(2)).toHaveText('');await fits(page)
})

test('rowspan groups stay intact across pagination and archive round trips',async({page})=>{
 const result=await page.evaluate(async()=>{const f=window.__facet,d=structuredClone(f.getDocument()),cell=(text:string,attrs={})=>({type:'tableCell',attrs,content:[{type:'paragraph',content:[{type:'text',text}]}]});d.content=[{type:'table',attrs:{id:crypto.randomUUID()},content:Array.from({length:35},(_,i)=>[{type:'tableRow',content:[cell('GROUP '+i,{rowspan:2,colwidth:[150]}),cell('FIRST '+i,{colwidth:[900]})]},{type:'tableRow',content:[cell('SECOND '+i,{colwidth:[900]})]}]).flat()}];f.load(d);const tablePath='/node_modules/.vite/deps/@tiptap_pm_tables.js',archivePath='/src/core/archive.ts';const {TableMap}=await import(/* @vite-ignore */tablePath);const problems:any[]=[];f.editor.state.doc.descendants((n:any)=>{if(n.type.name==='table'&&TableMap.get(n).problems)problems.push(TableMap.get(n).problems)});const saved=await (await import(/* @vite-ignore */archivePath)).decodeDocument(await f.encode());return {problems,rows:saved.content[0].content.length,pages:f.editor.state.doc.childCount}})
 expect(result.problems).toEqual([]);expect(result.rows).toBe(70);expect(result.pages).toBeGreaterThan(1);await fits(page)
})

test('desktop clipboard image data works with HTML and explicit image paste under CSP',async({page})=>{
 await page.addInitScript(html=>{const w=window as any;const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;const image=canvas.toDataURL('image/png');w.facetDesktop={readClipboard:async()=>({text:'preview',html,image}),recent:async()=>[],recoveries:async()=>[],recovery:async()=>({ok:true}),onClose:()=>()=>{},onOpen:()=>()=>{}}},office)
 await page.reload();await page.waitForFunction(()=>window.__facet?.editor);await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph'}];f.load(d)});await page.locator('.tiptap p').click({button:'right'});await page.getByRole('menuitem',{name:'粘贴（保留格式）',exact:true}).click();await expect(page.locator('.tiptap table')).toHaveCount(1);await fits(page)
 await page.locator('.tiptap td').first().click({button:'right'});await page.getByRole('menuitem',{name:'粘贴为图片'}).click();await expect(page.locator('.tiptap .image-block')).toHaveCount(1);await expect(page.locator('.tiptap table')).toHaveCount(1)
})
