import { test,expect } from '@playwright/test'
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('facet-guide-seen','true'));await page.goto('/');await page.waitForFunction(()=>window.__facet?.editor);await page.evaluate(()=>document.fonts.ready)})
test('A4 geometry and side panels do not change wrapping',async({page})=>{
  const before=await page.locator('.facet-page').first().evaluate(e=>({width:(e as HTMLElement).offsetWidth,height:(e as HTMLElement).offsetHeight,text:e.textContent}))
  expect(before.width).toBe(794);expect(before.height).toBe(1123)
  await page.getByTitle('收起组件').click();await page.getByTitle('收起导航').click()
  const after=await page.locator('.facet-page').first().evaluate(e=>({width:(e as HTMLElement).offsetWidth,height:(e as HTMLElement).offsetHeight,text:e.textContent}));expect(after).toEqual(before)
})
test('mouse insertion preserves paragraph position, with undo',async({page})=>{
  await page.evaluate(()=>{const f=window.__facet;let pos=0;f.editor.state.doc.descendants((n:any,p:number)=>{if(n.type.name==='paragraph'&&n.textContent.startsWith('这里是'))pos=p+1+3});f.editor.commands.setTextSelection(pos);f.editor.commands.focus()})
  await page.locator('[data-component="important"]').click();await expect(page.locator('.callout[data-variant="important"]')).toHaveCount(1)
  const types=await page.evaluate(()=>window.__facet.getDocument().content.map((n:any)=>n.type));expect(types.filter((t:string)=>t==='callout')).toHaveLength(3)
  await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.locator('.callout[data-variant="important"]')).toHaveCount(0)
})
test('formula panel normalizes delimiters and saves rendered formula',async({page})=>{
  await page.locator('[data-component="equation"]').click();await page.locator('.math-source').fill('$$\\frac{a}{b}$$');await expect(page.locator('.math-preview .katex')).toHaveCount(1)
  await page.getByRole('button',{name:/完成/}).click();await expect(page.locator('.math-block')).toHaveCount(2)
  expect(await page.evaluate(()=>window.__facet.getDocument().content.filter((n:any)=>n.type==='mathBlock').at(-1).attrs.latex)).toBe('\\frac{a}{b}')
})
test('long paragraphs and callouts paginate without modifying the source',async({page})=>{
  const expected=await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());const p=(text:string)=>({type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text}]});d.content=[p('中英文 pagination test。'.repeat(450)),{type:'callout',attrs:{id:crypto.randomUUID(),variant:'reflection',title:'长思考',icon:'brain',color:'royalpurple'},content:Array.from({length:22},(_,i)=>p(`第 ${i} 段。`+'跨页也保持完整。'.repeat(30)))},p('END-MARKER')];const json=JSON.stringify(d.content);f.load(d);return json})
  await page.waitForTimeout(500)
  expect(await page.locator('.facet-page').count()).toBeGreaterThan(3)
  expect(await page.evaluate(()=>window.__facet.getLayout().issues)).toEqual([])
  const text=await page.locator('.page-content').allTextContents();expect(text.join('')).toContain('END-MARKER')
  const overflows=await page.locator('.facet-page').evaluateAll(nodes=>nodes.map(n=>{const p=n as HTMLElement;const content=p.querySelector('.page-content')!;const children=Array.from(content.children);const last=children.at(-1);return last?last.getBoundingClientRect().bottom-(p.getBoundingClientRect().bottom-parseFloat(getComputedStyle(p).paddingBottom)*p.getBoundingClientRect().width/p.offsetWidth):0}));expect(Math.max(...overflows)).toBeLessThan(3)
  // Editing a later page must preserve all earlier fragments in canonical JSON.
  const length=await page.evaluate(()=>{const f=window.__facet;f.editor.commands.focus('end');f.editor.commands.insertContent(' EDIT');return JSON.stringify(f.getDocument().content)})
  expect(length).toContain('中英文 pagination test。');expect(length).toContain('第 21 段。');expect(length).toContain('END-MARKER EDIT')
})
test('manual page break and long table header repetition',async({page})=>{
  await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());const p=(text:string)=>({type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text}]});d.content=[p('FIRST'),{type:'pageBreak',attrs:{id:crypto.randomUUID()}},p('SECOND'),{type:'table',attrs:{id:crypto.randomUUID()},content:Array.from({length:60},(_,i)=>({type:'tableRow',attrs:{id:crypto.randomUUID()},content:[{type:i===0?'tableHeader':'tableCell',attrs:{id:crypto.randomUUID()},content:[p(i===0?'HEADER':`ROW-${i}`)]}]}))}];f.load(d)})
  await page.waitForTimeout(250);await expect(page.locator('.facet-page').nth(1)).toContainText('SECOND');expect(await page.locator('th').count()).toBeGreaterThan(1)
  await page.evaluate(()=>{const f=window.__facet;f.editor.commands.focus('end');f.editor.commands.insertContent('x')})
  await page.getByRole('button',{name:'＋ 列',exact:true}).click()
  expect(await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='table').content.every((r:any)=>r.content.length===2))).toBe(true)
  await page.getByRole('button',{name:'删除列',exact:true}).click()
  expect(await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='table').content.every((r:any)=>r.content.length===1))).toBe(true)
  const rows=await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='table').content.length);expect(rows).toBe(60)
})
test('metadata changes appear on paper',async({page})=>{
  await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByLabel('文档标题',{exact:true}).fill('新的研究记录');await page.getByLabel('页眉',{exact:true}).fill('PROJECT ALPHA');await page.getByRole('button',{name:'完成',exact:true}).click()
  await expect(page.locator('.document-title h1')).toHaveText('新的研究记录');await expect(page.locator('.page-header').first()).toHaveText('PROJECT ALPHA')
})
test('slash inserts using the same registry',async({page})=>{
  await page.locator('.page-content > p').last().click();await page.keyboard.type('/imp');await expect(page.locator('.slash-menu')).toBeVisible();await page.keyboard.press('Enter');await expect(page.locator('.callout[data-variant="important"]')).toHaveCount(1)
})

test('complete slash menu scrolls to later commands and quick commands use arrow keys',async({page})=>{
  await page.locator('.page-content > p').last().click();await page.keyboard.type('/')
  expect(await page.locator('.slash-menu button').count()).toBeGreaterThan(25)
  for(let i=0;i<10;i++)await page.keyboard.press('ArrowDown')
  await expect(page.locator('.slash-menu button.active')).toBeInViewport()
  await page.keyboard.press('Escape');await page.keyboard.press('Backspace')
  await page.keyboard.press('Control+Shift+P');const input=page.getByRole('combobox',{name:'搜索快速命令'})
  await input.fill('标题');await page.keyboard.press('ArrowDown');await expect(page.getByRole('option',{selected:true})).toContainText('二级标题')
  await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(await page.evaluate(()=>window.__facet.getDocument().content.filter((n:any)=>n.type==='heading'&&n.attrs.level===2).length)).toBe(2)
})

test('table dimensions, per-column alignment and row/column buttons work',async({page})=>{
  await page.locator('[data-component="table"]').click()
  await page.getByLabel('表格行数').fill('10');await page.getByLabel('表格列数').fill('3')
  await page.getByLabel('第 2 列对齐').selectOption('center');await page.getByLabel('第 3 列对齐').selectOption('right')
  await page.getByRole('button',{name:'插入表格',exact:true}).click()
  await expect(page.locator('.ProseMirror table tr')).toHaveCount(10)
  await expect(page.locator('.ProseMirror table tr').nth(1).locator('td').nth(1)).toHaveCSS('text-align','center')
  await page.locator('.ProseMirror table tr').nth(1).locator('td').nth(1).click()
  await page.getByRole('button',{name:'右对齐',exact:true}).click()
  expect(await page.locator('.ProseMirror table tr').evaluateAll(rows=>rows.every(r=>(r.children[1] as HTMLElement).style.textAlign==='right'))).toBe(true)
  await page.getByRole('button',{name:'＋ 行',exact:true}).click();await expect(page.locator('.ProseMirror table tr')).toHaveCount(11)
  expect(await page.locator('.ProseMirror table tr').evaluateAll(rows=>rows.every(r=>(r.children[1] as HTMLElement).style.textAlign==='right'))).toBe(true)
  await page.getByRole('button',{name:'删除行',exact:true}).click();await expect(page.locator('.ProseMirror table tr')).toHaveCount(10)
  await page.getByRole('button',{name:'＋ 列',exact:true}).click();await expect(page.locator('.ProseMirror table tr').first().locator('th')).toHaveCount(4)
  await page.getByRole('button',{name:'删除列',exact:true}).click();await expect(page.locator('.ProseMirror table tr').first().locator('th')).toHaveCount(3)
})

test('subfigure descriptions persist in the document and exported HTML',async({page})=>{
  await page.getByRole('button',{name:'多媒体',exact:true}).click();await page.locator('[data-component="subfigure"]').click()
  const image={name:'figure.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')}
  await page.locator('input[type=file][multiple]').setInputFiles([image,{...image,name:'figure2.png'}])
  await expect(page.locator('.ProseMirror .subfigure')).toHaveCount(1)
  await page.locator('.ProseMirror .subfigure').dblclick();await page.getByLabel('子图 1 说明').fill('输入图像');await page.getByLabel('子图 2 说明').fill('重建结果')
  await page.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.locator('.ProseMirror .subfigure figcaption').nth(1)).toHaveText('重建结果')
  expect(await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='subfigure').attrs.items[0].caption)).toBe('输入图像')
  expect(await page.evaluate(()=>window.__facet.exportHTML())).toContain('重建结果')
})

test('double columns edit independently, accept images and resize',async({page})=>{
  await page.locator('.page-content > p').last().click();await page.getByRole('button',{name:'多媒体',exact:true}).click();await page.locator('[data-component="columns"]').click()
  const columns=page.locator('.ProseMirror .two-columns');await expect(columns).toHaveCount(1)
  await columns.locator('.column-content').first().locator('p').click();await page.keyboard.type('LEFT TEXT')
  await columns.locator('.column-content').nth(1).locator('p').click();await page.keyboard.type('RIGHT TEXT')
  await page.locator('.columns-editor .column-content p').first().dblclick();await page.getByLabel('左栏宽度').fill('65');await page.getByRole('button',{name:'应用',exact:true}).click()
  await expect(columns).toHaveAttribute('data-ratio','65')
  await columns.locator('.column-content').nth(1).locator('p').click();await page.locator('[data-component="image"]').click()
  await page.locator('input[type=file]').nth(1).setInputFiles({name:'image.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')})
  await expect(columns.locator('.column-content').nth(1).locator('img')).toHaveCount(1)
  await expect(columns.locator('.column-content').first()).toContainText('LEFT TEXT')
})

test('long double columns paginate without mixing or losing their content',async({page})=>{
  const expected=await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());const p=(text:string)=>({type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text}]});d.content=[{type:'columns',attrs:{id:crypto.randomUUID(),ratio:40,gap:20},content:[{type:'column',attrs:{id:crypto.randomUUID()},content:[p('左栏记录。'.repeat(1800))]},{type:'column',attrs:{id:crypto.randomUUID()},content:[p('右栏记录。'.repeat(700))]}]},p('END')];f.load(d);return d.content[0].content.map((n:any)=>n.content[0].content[0].text)})
  expect(await page.locator('.ProseMirror .two-columns').count()).toBeGreaterThan(2)
  expect(await page.evaluate(()=>window.__facet.getLayout().issues)).toEqual([])
  const actual=await page.evaluate(()=>{const f=window.__facet;f.editor.commands.focus('end');f.editor.commands.insertContent('!');return f.getDocument().content[0].content.map((n:any)=>n.content.flatMap((p:any)=>p.content??[]).map((t:any)=>t.text??'').join(''))})
  expect(actual).toEqual(expected)
})

test('default cover, flexible TOC leaders and working exported anchors',async({page})=>{
  await expect(page.locator('.ProseMirror .default-cover-image')).toBeVisible()
  const first=page.locator('.ProseMirror .toc-line').first();const target=await first.getAttribute('data-toc-target')
  await first.click();expect(await page.evaluate(()=>window.__facet.editor.state.selection.$from.parent.attrs.id)).toBe(target)
  const html=await page.evaluate(()=>window.__facet.exportHTML());expect(html).toContain(`href="#block-${target}"`);expect(html).toContain(`id="block-${target}"`)
  const leaders=await page.locator('.ProseMirror .toc-line').evaluateAll(rows=>rows.map(r=>{const leader=r.querySelector('.toc-leader')!.getBoundingClientRect(),num=r.querySelector('.toc-page')!.getBoundingClientRect();return num.left-leader.right}))
  leaders.forEach(gap=>expect(gap).toBeLessThan(15))
  const preview=await page.context().newPage();await preview.setContent(html!);await preview.evaluate(()=>document.fonts.ready)
  await preview.locator('.facet-page').first().screenshot({path:'test-results/updated-cover.png'})
  await preview.locator('.document-toc').screenshot({path:'test-results/updated-contents.png'});await preview.close()
})

test('empty lists and code blocks stay inside the printable body',async({page})=>{
  await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());const p=()=>({type:'paragraph',attrs:{id:crypto.randomUUID()}});d.content=Array.from({length:36},(_,i)=>i%3===0?{type:'codeBlock',attrs:{id:crypto.randomUUID(),language:'python'},content:i%2?[{type:'text',text:'print(1)\n'}]:[]}:{type:i%3===1?'bulletList':'orderedList',attrs:{id:crypto.randomUUID()},content:[{type:'listItem',attrs:{id:crypto.randomUUID()},content:[p()]}]});f.load(d)})
  await page.waitForTimeout(400)
  const overflows=await page.locator('.facet-page').evaluateAll(pages=>pages.flatMap(p=>{const page=p as HTMLElement,scale=page.getBoundingClientRect().width/page.offsetWidth,bottom=page.getBoundingClientRect().bottom-parseFloat(getComputedStyle(page).paddingBottom)*scale;return Array.from(page.querySelector('.page-content')!.children).map(n=>n.getBoundingClientRect().bottom-bottom)}))
  expect(Math.max(...overflows)).toBeLessThan(2)
  expect(await page.evaluate(()=>window.__facet.getLayout().issues)).toEqual([])
})

test('code language is directly editable and persists across reflow',async({page})=>{
  await page.locator('[data-component="code"]').click()
  const code=page.locator('.ProseMirror .code-editor-node').last()
  await code.getByLabel('代码语言').selectOption('javascript')
  await code.getByLabel('代码编辑区').fill('const answer = 42;\n')
  await expect(code.getByLabel('代码语言')).toHaveValue('javascript')
  expect(await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='codeBlock').attrs.language)).toBe('javascript')
  await expect(code.locator('.tok-keyword')).toHaveText('const')
})

test('italic, link dialog and writing toolbar undo work',async({page})=>{
  await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph',attrs:{id:'format-test'},content:[{type:'text',text:'测试斜体与链接'}]}];f.load(d);f.editor.commands.setTextSelection({from:2,to:6});f.editor.view.focus()})
  await page.getByRole('button',{name:'斜体',exact:true}).click()
  await expect(page.locator('.ProseMirror em')).toHaveCSS('font-synthesis','style')
  await page.getByRole('button',{name:'链接',exact:true}).click()
  await page.getByLabel('链接地址').fill('https://example.org/research')
  await page.getByRole('button',{name:'应用链接',exact:true}).click()
  await expect(page.locator('.ProseMirror a')).toHaveAttribute('href','https://example.org/research')
  const opened=await page.evaluate(()=>{let opened='';const previous=window.facetDesktop;window.facetDesktop={openExternal:async(url:string)=>{opened=url}} as any;document.querySelector('.ProseMirror a')!.dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:true}));window.facetDesktop=previous;return opened})
  expect(opened).toBe('https://example.org/research')
  await expect(page.locator('.format-toolbar').getByRole('button',{name:'撤销',exact:true})).toBeVisible()
  await page.locator('.format-toolbar').getByRole('button',{name:'撤销',exact:true}).click()
  await expect(page.locator('.ProseMirror a')).toHaveCount(0)
})

test('column divider drags and grid tables follow the theme',async({page})=>{
  await page.locator('.page-content > p').last().click();await page.getByRole('button',{name:'多媒体',exact:true}).click();await page.locator('[data-component="columns"]').click()
  const handle=page.getByRole('separator',{name:'拖动调整双栏宽度'});const rect=await handle.boundingBox()
  await page.mouse.move(rect!.x+rect!.width/2,rect!.y+10);await page.mouse.down();await page.mouse.move(rect!.x+60,rect!.y+10,{steps:8});await page.mouse.up()
  expect(Number(await handle.getAttribute('aria-valuenow'))).toBeGreaterThan(55)
  await handle.focus();await page.keyboard.press('ArrowLeft')
  const ratio=Number(await handle.getAttribute('aria-valuenow'))
  expect(await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='columns').attrs.ratio)).toBe(ratio)
  await page.evaluate(()=>window.__facet.editor.commands.focus('end'))
  await page.getByRole('button',{name:'收藏',exact:true}).click();await page.locator('[data-component="table"]').click()
  await page.getByLabel('新表格样式').selectOption('grid');await page.getByRole('button',{name:'插入表格',exact:true}).click()
  await expect(page.locator('.ProseMirror table')).toHaveAttribute('data-table-style','grid')
  await expect(page.locator('.ProseMirror th').first()).toHaveCSS('color','rgb(255, 255, 255)')
  expect(await page.evaluate(()=>window.__facet.exportHTML())).toContain('data-table-style="grid"')
})

test('component colors show swatches and custom colors survive export',async({page})=>{
  await page.locator('.ProseMirror .callout-title').first().click()
  const dialog=page.getByRole('dialog',{name:'编辑样式'})
  await expect(dialog.getByRole('button',{name:'学术蓝',exact:true}).locator('i')).toHaveCSS('background-color','rgb(18, 59, 120)')
  await dialog.getByLabel('自定义组件颜色').fill('#2e7799')
  await dialog.getByRole('button',{name:'应用',exact:true}).click()
  await expect(page.locator('.ProseMirror .callout').first()).toHaveCSS('--callout-color','#2e7799')
  const html=await page.evaluate(()=>window.__facet.exportHTML());expect(/--callout-color:\s*#2e7799/.test(html)).toBe(true)
  await page.getByRole('button',{name:'基础',exact:true}).click();await page.locator('[data-component="icon"]').click()
  await expect(page.getByRole('dialog').getByText('Lightbulb',{exact:true})).toHaveCSS('font-size','12px')
  await page.getByRole('dialog').screenshot({path:'test-results/icon-picker.png'})
})

test('new document offers portrait and landscape without changing insertion commands',async({page})=>{
  const id=await page.evaluate(()=>window.__facet.getDocument().id)
  await page.getByRole('button',{name:/新建文档/}).click()
  await expect(page.getByRole('radio',{name:/竖版/})).toHaveAttribute('aria-checked','true')
  await page.getByRole('radio',{name:/横版/}).click()
  await page.getByRole('dialog',{name:'新建文档'}).screenshot({path:'test-results/new-document-orientation.png'})
  await page.getByRole('button',{name:'取消',exact:true}).click()
  expect(await page.evaluate(()=>window.__facet.getDocument().id)).toBe(id)
  await page.getByRole('button',{name:/新建文档/}).click();await page.getByRole('radio',{name:/横版/}).click();await page.getByRole('button',{name:'创建文档',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'设置'})).toBeVisible()
  await page.getByLabel('文档标题',{exact:true}).fill('横版研究笔记')
  await page.getByRole('button',{name:'完成',exact:true}).click()
  expect(await page.evaluate(()=>window.__facet.getDocument().page.orientation)).toBe('landscape')
  await expect(page.locator('.document-title h1')).toHaveText('横版研究笔记')
  const geometry=await page.locator('.facet-page').first().evaluate(e=>({w:(e as HTMLElement).offsetWidth,h:(e as HTMLElement).offsetHeight}))
  expect(geometry.w/geometry.h).toBeCloseTo(16/9,2)
  await page.locator('.page-content > p').last().click();await page.locator('[data-component="important"]').click()
  await expect(page.locator('.callout[data-variant="important"]')).toHaveCount(1)
  await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(page.locator('.callout[data-variant="important"]')).toHaveCount(0)
  await page.locator('.page-content > p').last().click();await page.keyboard.type('/imp');await page.keyboard.press('Enter')
  await expect(page.locator('.callout[data-variant="important"]')).toHaveCount(1)
  await expect(page.locator('.document-title h1')).toHaveText('横版研究笔记')
  const coverPreview=await page.context().newPage();await coverPreview.setContent(await page.evaluate(()=>window.__facet.exportHTML()));await coverPreview.evaluate(()=>document.fonts.ready)
  await coverPreview.locator('.facet-page').first().screenshot({path:'test-results/landscape-cover.png'});await coverPreview.close()
  await page.keyboard.press('Control+n');await expect(page.getByRole('dialog',{name:'新建文档'})).toBeVisible()
  await page.getByRole('button',{name:'创建文档',exact:true}).click();await page.getByRole('button',{name:'不保存',exact:true}).click();await page.getByRole('button',{name:'完成',exact:true}).click()
  expect(await page.evaluate(()=>window.__facet.getDocument().page.orientation)).toBe('portrait')
  expect(await page.locator('.facet-page').first().evaluate(e=>(e as HTMLElement).offsetWidth)).toBe(794)
})

test('landscape pagination preserves content and PDF page dimensions',async({page})=>{
  await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.page.orientation='landscape';d.page.margin=18;const p=(text:string)=>({type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text}]});d.content=[p('横版文字。'.repeat(1500)),{type:'columns',attrs:{id:crypto.randomUUID(),ratio:55,gap:24},content:[{type:'column',attrs:{id:crypto.randomUUID()},content:[p('LEFT '.repeat(800))]},{type:'column',attrs:{id:crypto.randomUUID()},content:[p('RIGHT '.repeat(400))]}]},p('END')];f.load(d)})
  await page.waitForTimeout(300)
  expect(await page.locator('.facet-page').count()).toBeGreaterThan(3)
  expect(await page.evaluate(()=>window.__facet.getLayout().issues)).toEqual([])
  const overflow=await page.locator('.facet-page').evaluateAll(nodes=>Math.max(...nodes.flatMap(e=>{const el=e as HTMLElement,rect=el.getBoundingClientRect(),scale=rect.width/el.offsetWidth;return Array.from(el.querySelector('.page-content')!.children).map(c=>c.getBoundingClientRect().bottom-(rect.bottom-parseFloat(getComputedStyle(el).paddingBottom)*scale))})))
  expect(overflow).toBeLessThan(2)
  const html=await page.evaluate(()=>window.__facet.exportHTML());expect(html.includes('@page{size:320mm 180mm')).toBe(true)
  const preview=await page.context().newPage();await preview.setContent(html);await preview.evaluate(()=>document.fonts.ready)
  const size=await preview.locator('.facet-page').first().evaluate(e=>({w:(e as HTMLElement).offsetWidth,h:(e as HTMLElement).offsetHeight}));expect(size.w/size.h).toBeCloseTo(16/9,2)
  const pdf=await preview.pdf({preferCSSPageSize:true,printBackground:true});const boxes=[...pdf.toString('latin1').matchAll(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/g)]
  expect(boxes.length).toBe(await page.locator('.facet-page').count());for(const box of boxes)expect(Number(box[1])/Number(box[2])).toBeCloseTo(16/9,2)
  await preview.close()
  await page.evaluate(()=>{const f=window.__facet;f.editor.commands.focus('end');f.editor.commands.insertContent('!')})
  expect(await page.evaluate(()=>window.__facet.getDocument().content[0].content.map((n:any)=>n.text||'').join(''))).toBe('横版文字。'.repeat(1500))
})

test('table size stays locked after click and manual input',async({page})=>{
  await page.locator('[data-component="table"]').click()
  await page.getByRole('button',{name:'5 行 6 列',exact:true}).click()
  await page.getByRole('button',{name:'8 行 8 列',exact:true}).hover()
  await expect(page.getByLabel('表格行数')).toHaveValue('5');await expect(page.getByLabel('表格列数')).toHaveValue('6')
  await page.getByLabel('表格行数').fill('12');await page.getByRole('button',{name:'1 行 1 列',exact:true}).hover()
  await expect(page.getByLabel('表格行数')).toHaveValue('12')
  await page.getByRole('button',{name:'2 行 4 列',exact:true}).click()
  await page.getByRole('button',{name:'插入表格',exact:true}).click()
  expect(await page.evaluate(()=>window.__facet.getDocument().content.find((n:any)=>n.type==='table').content.length)).toBe(2)
})

test('task text is editable beside checkbox and survives pagination and checking',async({page})=>{
  await page.locator('[data-component="task"]').click()
  const task=page.locator('.ProseMirror li[data-type="taskItem"]');const paragraph=task.locator('p')
  await paragraph.click();await page.keyboard.insertText('今天完成实验')
  await expect(paragraph).toHaveText('今天完成实验')
  const boxes=await task.evaluate(e=>{const a=e.querySelector('input')!.getBoundingClientRect(),b=e.querySelector('p')!.getBoundingClientRect();return {a:a.right,b:b.left}})
  expect(boxes.b).toBeGreaterThan(boxes.a)
  await task.locator('input').check();await expect(paragraph).toHaveText('今天完成实验')
  await paragraph.click();await page.keyboard.press('End');await page.keyboard.press('Enter');await page.keyboard.insertText('下一项')
  await expect(page.locator('.ProseMirror li[data-type="taskItem"]')).toHaveCount(2)
})

test('parts increment, appear in outline, and remain valid in archive',async({page})=>{
  await page.getByRole('button',{name:'基础',exact:true}).click()
  await expect(page.locator('[data-component="semantic"]')).toContainText('/iconlist')
  await expect(page.locator('[data-component="badge"]')).toContainText('/state')
  await page.locator('[data-component="part"]').click();await expect(page.locator('.outline')).toContainText('Part 1')
  await page.keyboard.press('End');await page.keyboard.press('Enter');await page.keyboard.insertText('部分正文')
  await page.locator('[data-component="part"]').click();await expect(page.locator('.outline')).toContainText('Part 2')
  const result=await page.evaluate(async()=>{const f=window.__facet;const archivePath='/src/core/archive.ts';const {decodeDocument}=await import(/* @vite-ignore */ archivePath);const d=await decodeDocument(await f.encode());return d.content.filter((n:any)=>n.type==='part').map((n:any)=>n.content.map((c:any)=>c.text).join(''))})
  expect(result).toEqual(['Part 1','Part 2'])
})

test('Beamer keeps long paragraphs, lists and tables across continuation slides',async({page})=>{
  const before=await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());const p=(text:string)=>({type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text}]});d.content=[{type:'part',attrs:{id:crypto.randomUUID()},content:[{type:'text',text:'Part 1'}]},{type:'heading',attrs:{id:crypto.randomUUID(),level:3},content:[{type:'text',text:'长内容'}]},p('保留全部研究内容。'.repeat(500)),{type:'bulletList',attrs:{id:crypto.randomUUID()},content:Array.from({length:25},(_,i)=>({type:'listItem',attrs:{id:crypto.randomUUID()},content:[p(`LIST-${i}`)]}))},{type:'table',attrs:{id:crypto.randomUUID()},content:Array.from({length:30},(_,i)=>({type:'tableRow',attrs:{id:crypto.randomUUID()},content:[{type:i===0?'tableHeader':'tableCell',attrs:{id:crypto.randomUUID()},content:[p(i===0?'HEADER':`ROW-${i}`)]}]}))},{type:'heading',attrs:{id:crypto.randomUUID(),level:3},content:[{type:'text',text:'结束'}]},p('END-MARKER')];f.load(d);return JSON.stringify(f.getDocument())})
  const result=await page.evaluate(()=>window.__facet.exportBeamer('MY LAB'))
  expect(result.pageCount).toBeGreaterThan(5)
  expect(await page.evaluate(()=>JSON.stringify(window.__facet.getDocument()))).toBe(before)
  await page.setContent(result.html);await page.evaluate(()=>document.fonts.ready)
  await expect(page.locator('.beamer-part')).toContainText('Part 1')
  expect((await page.locator('.beamer-frame-title').allTextContents()).some(t=>t.includes('（续'))).toBe(true)
  const body=await page.locator('.beamer-body').allTextContents();expect(body.join('')).toContain('ROW-29');expect(body.join('')).toContain('LIST-24');expect(body.join('')).toContain('END-MARKER')
  expect(body.join('').match(/保留全部研究内容。/g)?.length).toBe(500)
  expect(await page.locator('.beamer-slide').count()).toBe(result.pageCount)
  expect(await page.locator('.beamer-body').evaluateAll(nodes=>nodes.every(n=>n.scrollHeight<=n.clientHeight+3&&n.scrollWidth<=n.clientWidth+3))).toBe(true)
  await page.screenshot({path:'test-results/beamer-preview.png',fullPage:false})
  await page.pdf({path:'test-results/beamer-preview.pdf',preferCSSPageSize:true,printBackground:true})
})


test('Beamer uses higher headings as context and preserves preamble and empty H3',async({page})=>{
  const result=await page.evaluate(async()=>{const f=window.__facet,d=structuredClone(f.getDocument());const h=(level:number,text:string)=>({type:'heading',attrs:{id:crypto.randomUUID(),level},content:[{type:'text',text}]});d.content=[h(1,'章节'),h(2,'背景'),{type:'paragraph',content:[{type:'text',text:'标题前的引言'}]},h(3,'第一帧'),{type:'paragraph',content:[{type:'text',text:'核心结论'}]},h(3,'待补充')];f.load(d);return f.exportBeamer('')})
  await page.setContent(result.html)
  expect(await page.locator('.beamer-frame-title').allTextContents()).toEqual(['背景','第一帧','待补充'])
  await expect(page.locator('.beamer-body').nth(1)).toContainText('标题前的引言')
  expect(result.pageCount).toBe(4)
})
