import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('facet-guide-seen','true'));await page.goto('/');await page.waitForFunction(()=>window.__facet?.editor);await page.evaluate(()=>document.fonts.ready)})
async function blank(page:any){await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph',attrs:{id:crypto.randomUUID()}}];f.load(d)});await page.locator('.tiptap p').click()}
test('paired dollars, brackets and closing characters keep the cursor inside',async({page})=>{
 await blank(page);await page.keyboard.type('$');expect(await page.evaluate(()=>({text:window.__facet.editor.state.selection.$from.parent.textContent,offset:window.__facet.editor.state.selection.$from.parentOffset}))).toEqual({text:'$$',offset:1})
 await page.keyboard.type('$');expect(await page.evaluate(()=>({text:window.__facet.editor.state.selection.$from.parent.textContent,offset:window.__facet.editor.state.selection.$from.parentOffset}))).toEqual({text:'$$$$',offset:2})
 await page.keyboard.type('x+y$$');await expect(page.locator('.tiptap .math-block')).toHaveCount(1)
 await blank(page);await page.keyboard.type('$$');await page.keyboard.press('Enter');await expect(page.getByRole('dialog',{name:'编辑公式'})).toBeVisible();await page.getByRole('button',{name:'取消',exact:true}).click();
 await blank(page);await page.keyboard.type('value $x^2$');await expect(page.locator('.tiptap .math-inline')).toHaveCount(1)
 await blank(page);await page.keyboard.type('(');await expect(page.locator('.tiptap p')).toHaveText('()');await page.keyboard.type('a)');await expect(page.locator('.tiptap p')).toHaveText('(a)')
 await blank(page);await page.keyboard.insertText('【');await expect(page.locator('.tiptap p')).toHaveText('【】');await page.keyboard.press('Backspace');await expect(page.locator('.tiptap p')).toHaveText('')
})
test('find searches formatted text and code, cycles, and leaves export clean',async({page})=>{
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph',content:[{type:'text',text:'alpha '},{type:'text',text:'alpha',marks:[{type:'bold'}]}]},{type:'codeBlock',attrs:{id:crypto.randomUUID()},content:[{type:'text',text:'alpha()'}]}];f.load(d)})
 await page.keyboard.press('Control+f');await page.getByLabel('搜索文档').fill('alpha');await expect(page.getByRole('search')).toContainText('1 / 3');await expect(page.locator('.tiptap .search-active')).toHaveCount(1)
 await page.getByLabel('搜索文档').press('Enter');await expect(page.getByRole('search')).toContainText('2 / 3');await page.getByLabel('搜索文档').press('Enter');await expect(page.getByRole('search')).toContainText('3 / 3');await expect(page.locator('.tiptap .search-code-active')).toHaveCount(1)
 const html=await page.evaluate(()=>window.__facet.exportHTML());expect(html).not.toMatch(/class="[^"]*search-active/);expect(html).not.toContain('<mark class="search-match"')
 await page.getByLabel('搜索文档').press('Escape');await expect(page.getByRole('search')).toHaveCount(0)
})
test('code line numbers continue across paper and Beamer pages',async({page})=>{
 const result=await page.evaluate(async()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'codeBlock',attrs:{id:crypto.randomUUID(),language:'python'},content:[{type:'text',text:Array.from({length:130},(_,i)=>'print('+i+')').join('\n')}]}];f.load(d);return {numbers:Array.from(f.editor.view.dom.querySelectorAll('.code-line')).map((e:any)=>Number(e.dataset.line)),html:(await f.exportBeamer()).html,source:f.getDocument().content[0].content[0].text}})
 expect(result.numbers).toEqual(Array.from({length:130},(_,i)=>i+1));expect(result.source.split('\n')).toHaveLength(130);await page.setContent(result.html);expect(await page.locator('.code-line').evaluateAll(es=>es.map((e:any)=>Number(e.dataset.line)))).toEqual(Array.from({length:130},(_,i)=>i+1))
})
test('TOC level, category favorites and export defaults use the requested locations',async({page})=>{
 await expect(page.locator('.format-toolbar').getByRole('button',{name:'组件设置',exact:true})).toHaveCount(0);await expect(page.locator('.top-actions').getByRole('button',{name:'导出',exact:true})).toBeVisible();await page.locator('.sidebar-bottom').getByRole('button',{name:'设置',exact:true}).click()
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'目录',exact:true}).click();await page.getByLabel('目录显示到').selectOption('1');await expect(page.locator('.document-toc .toc-level-2')).toHaveCount(0)
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'收藏',exact:true}).click();await page.getByRole('navigation',{name:'收藏分类'}).getByRole('button',{name:/提示框/}).click();await expect(page.locator('.favorite-grid')).toContainText('实验');await expect(page.locator('.favorite-grid')).not.toContainText('一级标题')
 await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'导出',exact:true}).click();await page.getByRole('button',{name:'Beamer PDF',exact:true}).click();await page.getByRole('button',{name:'完成',exact:true}).click();await page.locator('.top-actions').getByRole('button',{name:'导出',exact:true}).click();await expect(page.getByRole('dialog',{name:'导出文档'})).toBeVisible();await expect(page.getByLabel('导出格式')).toHaveValue('beamer')
})
test('unsaved changes offer save, discard, cancel before a new file',async({page})=>{
 await blank(page);await page.keyboard.type('KEEP');const id=await page.evaluate(()=>window.__facet.getDocument().id);await page.getByRole('button',{name:/新建文档/}).click();await page.getByRole('button',{name:'创建文档',exact:true}).click();await expect(page.getByRole('dialog',{name:'保存更改？'})).toBeVisible();await page.getByRole('dialog',{name:'保存更改？'}).getByRole('button',{name:'取消',exact:true}).click();expect(await page.evaluate(()=>window.__facet.getDocument().id)).toBe(id)
 await page.getByRole('button',{name:'创建文档',exact:true}).click();await page.getByRole('button',{name:'不保存',exact:true}).click();await expect.poll(()=>page.evaluate(()=>window.__facet.getDocument().id)).not.toBe(id);await expect(page.getByRole('dialog',{name:'设置',exact:true})).toBeVisible()
})

test('search finds a phrase spanning a page boundary',async({page})=>{
 const query=await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text:Array.from({length:1600},(_,i)=>'word'+i).join(' ')}]}];f.load(d);const first=f.editor.state.doc.firstChild.firstChild.textContent;return d.content[0].content[0].text.slice(first.length-6,first.length+7)})
 await page.keyboard.press('Control+f');await page.getByLabel('搜索文档').fill(query);await expect(page.getByRole('search')).toContainText('1 / 1');await expect(page.locator('.tiptap .search-active')).toHaveCount(2)
})
test('folder tree expands and save decisions govern file switching and closing',async({page})=>{
 await page.addInitScript(()=>{const w=window as any;w.disk={saves:0,recoveries:0,cancelSave:true};w.facetDesktop={recent:async()=>[],recoveries:async()=>[],recovery:async()=>{w.disk.recoveries++;return {ok:true}},listFolder:async(path='')=>({root:'C:/Research',name:'Research',entries:path?[{kind:'file',name:'Notes.facet',path:'Experiments/Notes.facet'}]:[{kind:'folder',name:'Experiments',path:'Experiments'}]}),openWorkspaceFile:async()=>w.nextFile,onOpen:(cb:any)=>{w.openTest=cb;return()=>{}},onClose:(cb:any)=>{w.closeTest=cb;return()=>{}},save:async()=>{w.disk.saves++;return w.disk.cancelSave?null:{token:'saved',path:'C:/Research/Saved.facet',name:'Saved.facet'}},cancelClose:()=>w.disk.closed=false,closeReady:()=>w.disk.closed=true}})
 await page.reload();await page.waitForFunction(()=>window.__facet?.editor);await expect(page.locator('.brand')).toContainText('Research');await page.getByRole('treeitem',{name:'Experiments',exact:true}).click();await expect(page.getByRole('treeitem',{name:'Notes.facet'})).toBeVisible()
 await page.evaluate(async()=>{const w=window as any,p='/src/core/archive.ts',d=structuredClone(w.__facet.getDocument());d.id=crypto.randomUUID();d.metadata.title='Notes';w.nextFile={token:'next',path:'C:/Research/Experiments/Notes.facet',bytes:Array.from(await (await import(/* @vite-ignore */p)).encodeDocument(d))};w.__facet.editor.commands.insertContent('changed')})
 await expect.poll(()=>page.evaluate(()=>(window as any).disk.recoveries)).toBeGreaterThan(0);expect(await page.evaluate(()=>(window as any).disk.saves)).toBe(0)
 await page.getByRole('treeitem',{name:'Notes.facet'}).click();const dialog=page.getByRole('dialog',{name:'保存更改？'});await dialog.getByRole('button',{name:'保存',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).disk.saves)).toBe(1);await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'不保存',exact:true}).click();await expect(page.locator('.document-status')).toContainText('Notes');await expect(page.getByRole('treeitem',{name:'Notes.facet'})).toHaveAttribute('aria-selected','true')
 await page.evaluate(()=>{const w=window as any;w.__facet.editor.commands.insertContent('edited');w.closeTest()});await dialog.getByRole('button',{name:'取消',exact:true}).click();expect(await page.evaluate(()=>(window as any).disk.closed)).toBe(false)
 await page.evaluate(()=>{const w=window as any;w.disk.cancelSave=false;w.closeTest()});await dialog.getByRole('button',{name:'保存',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).disk.closed)).toBe(true)
})
