import {test,expect} from '@playwright/test'
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('facet-guide-seen','true'));await page.goto('/');await page.waitForFunction(()=>window.__facet?.editor);await page.evaluate(()=>document.fonts.ready)})
async function blank(page:any){await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'paragraph',attrs:{id:crypto.randomUUID()}}];f.load(d)});await page.locator('.tiptap p').click()}
test('dollar input and multiline Markdown paste produce editable math',async({page})=>{
 await blank(page);await page.keyboard.type('inline $x^2$');await expect(page.locator('.math-inline')).toHaveCount(1)
 await page.keyboard.press('Enter');await page.keyboard.type('$$x+y$$');await expect(page.locator('.math-block')).toHaveCount(1)
 await blank(page);await page.evaluate(()=>{const data=new DataTransfer();data.setData('text/plain','Before $a+b$\n$$\n\\frac{a}{b}\n$$\nAfter');window.__facet.editor.view.dom.dispatchEvent(new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true}))})
 await expect(page.locator('.math-inline')).toHaveCount(1);await expect(page.locator('.math-block')).toHaveCount(1);await expect(page.locator('.invalid-math')).toHaveCount(0);await expect(page.locator('.tiptap.document-content')).toContainText('After')
})
test('bare links, modifier feedback, favorites and quote colors persist',async({page})=>{
 await blank(page);await page.getByRole('button',{name:'链接',exact:true}).click();await page.getByLabel('链接地址').fill('example.org/path');await page.getByRole('button',{name:'应用链接'}).click();await expect(page.locator('.tiptap.document-content a')).toHaveAttribute('href','https://example.org/path')
 await page.keyboard.down('Control');await expect(page.locator('.tiptap.document-content a')).toHaveCSS('cursor','pointer');await page.keyboard.up('Control')
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('navigation',{name:'设置分类'}).getByRole('button',{name:'收藏',exact:true}).click();await page.getByLabel('结论',{exact:true}).check();await page.getByRole('button',{name:'完成',exact:true}).click();await expect(page.locator('[data-component="conclusion"]')).toBeVisible()
 await page.reload();await expect(page.locator('[data-component="conclusion"]')).toBeVisible();await page.getByRole('button',{name:'提示框',exact:true}).click();await expect(page.locator('[data-component="experiment"]')).toBeVisible()
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'blockquote',attrs:{id:crypto.randomUUID()},content:[{type:'paragraph',content:[{type:'text',text:'研究假设'}]}]}];f.load(d)})
 await page.locator('.tiptap blockquote').dblclick();await page.getByRole('button',{name:'翡翠绿',exact:true}).click();await page.getByRole('button',{name:'应用',exact:true}).click();await expect(page.locator('.tiptap blockquote')).toHaveAttribute('data-color','emeraldgreen')
 const result=await page.evaluate(async()=>{const path='/src/core/archive.ts';const {decodeDocument}=await import(/* @vite-ignore */path);return (await decodeDocument(await window.__facet.encode())).content[0].attrs.color});expect(result).toBe('emeraldgreen')
 await blank(page);await page.keyboard.type('/');await expect(page.locator('.slash-menu')).toBeVisible();await expect(page.locator('.slash-menu button').filter({hasText:/^正文/})).toHaveCount(0)
})
test('table columns resize at editor zoom and retain widths after layout and save',async({page})=>{
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'table',attrs:{id:crypto.randomUUID()},content:Array.from({length:3},(_,r)=>({type:'tableRow',content:Array.from({length:3},(_,c)=>({type:r?'tableCell':'tableHeader',content:[{type:'paragraph',content:[{type:'text',text:String(r)+String(c)}]}]}))}))}];f.load(d)})
 const cell=page.locator('.tiptap.document-content th').first(),before=await cell.boundingBox();expect(before).not.toBeNull();await page.mouse.move(before!.x+before!.width-2,before!.y+10);await page.mouse.down();await page.mouse.move(before!.x+before!.width+45,before!.y+10);await page.mouse.up()
 await expect.poll(async()=>await cell.evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThan(before!.width+25)
 const result=await page.evaluate(async()=>{const path='/src/core/archive.ts';const {decodeDocument}=await import(/* @vite-ignore */path);window.__facet.paginate();const d=await decodeDocument(await window.__facet.encode());return d.content[0].content.map((r:any)=>r.content.map((c:any)=>c.attrs.colwidth))});expect(result[0][0][0]).toBeGreaterThan(result[0][1][0]);expect(result[1]).toEqual(result[0])
})
test('right-click supports formatted, plain and Markdown clipboard content',async({page})=>{
 await blank(page);await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=> 'Formula $z$'}})})
 await page.locator('.tiptap.document-content p').click({button:'right'});await expect(page.getByRole('menu')).toBeVisible();await page.getByRole('menuitem',{name:'粘贴为 Markdown'}).click();await expect(page.locator('.math-inline')).toHaveCount(1)
 await blank(page);await page.locator('.tiptap.document-content p').click({button:'right'});await page.getByRole('menuitem',{name:'粘贴为纯文本'}).click();await expect(page.locator('.math-inline')).toHaveCount(0);await expect(page.locator('.tiptap.document-content')).toContainText('Formula $z$')
})
test('multi-digit code line numbers stay on one line',async({page})=>{
 await page.evaluate(()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'codeBlock',attrs:{id:crypto.randomUUID(),language:'python'},content:[{type:'text',text:Array.from({length:105},(_,i)=>'print('+i+')').join('\n')}]}];f.load(d)})
 const number=page.locator('.code-line[data-line="10"]').first();expect(await number.evaluate(e=>getComputedStyle(e,'::before').whiteSpace)).toBe('nowrap');await expect(page.locator('.code-editor-node')).not.toHaveCount(0)
})
test('first launch opens the guide and settings can reopen it',async({page})=>{
 await page.evaluate(()=>localStorage.removeItem('facet-guide-seen'));await page.addInitScript(()=>localStorage.removeItem('facet-guide-seen'));await page.reload();await expect(page.getByRole('dialog',{name:'Facet 用法大全',exact:true})).toBeVisible();await expect(page.locator('iframe')).toHaveAttribute('src',/usage-guide.*pdf/);await page.getByRole('button',{name:'开始使用'}).click();expect(await page.evaluate(()=>localStorage.getItem('facet-guide-seen'))).toBe('true')
 await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByRole('button',{name:'说明书',exact:true}).click();await page.getByRole('button',{name:'打开可编辑示例',exact:true}).click();await expect(page.locator('.document-status')).toContainText('Facet 用法大全');await expect(page.locator('.tiptap.document-content')).toContainText('FACET-GUIDE-END')
})

test('copying image groups into another document preserves editable assets',async({page})=>{
 const result=await page.evaluate(async()=>{const f=window.__facet,canvas=document.createElement('canvas');canvas.width=3;canvas.height=3;const src=canvas.toDataURL('image/webp'),assetId=crypto.randomUUID(),id=crypto.randomUUID(),d=structuredClone(f.getDocument());d.assets={[assetId]:{name:'paste.webp',mime:'image/webp',data:src.split(',')[1]}};d.content=[{type:'subfigure',attrs:{id,columns:2,items:[{assetId,src,caption:'图一'},{assetId,src,caption:'图二'}]}}];f.load(d);const node=f.editor.state.doc.firstChild.firstChild,{dom}=f.editor.view.serializeForClipboard(f.editor.state.doc.slice(1,1+node.nodeSize));const target=structuredClone(d);target.id=crypto.randomUUID();target.assets={};target.content=[{type:'paragraph',attrs:{id:crypto.randomUUID()}}];f.load(target);f.editor.commands.focus('end');f.editor.view.pasteHTML(dom.innerHTML);const path='/src/core/archive.ts';const {decodeDocument}=await import(/* @vite-ignore */path);const saved=await decodeDocument(await f.encode()),group=saved.content.find((n:any)=>n.type==='subfigure');return {different:group.attrs.id!==id,captions:group.attrs.items.map((i:any)=>i.caption),assets:group.attrs.items.map((i:any)=>saved.assets[i.assetId]?.mime)}})
 expect(result).toEqual({different:true,captions:['图一','图二'],assets:['image/webp','image/webp']})
})
test('save conflicts retain the current document and cancel window closing',async({page})=>{
 await page.addInitScript(()=>{const w=window as any;w.testFileState={saves:[],conflict:true,cancelled:false};w.facetDesktop={recent:async()=>[],recoveries:async()=>[],recovery:async()=>({ok:true}),onOpen:(cb:any)=>{w.testOpen=cb;return()=>{}},onClose:(cb:any)=>{w.testClose=cb;return()=>{}},save:async(value:any)=>{w.testFileState.saves.push(value);return w.testFileState.conflict?{conflict:true}:{token:'saved',name:value.name+'.facet'}},closeReady:()=>{w.testFileState.closed=true},cancelClose:()=>{w.testFileState.cancelled=true}}})
 await page.reload();await page.waitForFunction(()=>window.__facet?.editor);await page.getByRole('button',{name:'保存文档',exact:true}).click();await expect(page.getByRole('status')).toContainText('文件已被其他应用修改')
 // A saved file with subsequent edits must stay open when saving fails.
 await page.evaluate(()=>{(window as any).testFileState.conflict=false});await page.getByRole('button',{name:'保存文档',exact:true}).click();await expect(page.locator('.document-status')).toContainText('已保存');const id=await page.evaluate(()=>window.__facet.getDocument().id)
 await page.evaluate(()=>window.__facet.editor.commands.insertContent('EDIT'));await page.evaluate(async()=>{const w=window as any;w.testFileState.conflict=true;const path='/src/core/archive.ts';const {encodeDocument}=await import(/* @vite-ignore */path);const next=structuredClone(w.__facet.getDocument());next.id=crypto.randomUUID();next.metadata.title='另一个文件';w.testOpen({token:'other',bytes:Array.from(await encodeDocument(next))})});await page.getByRole('dialog',{name:'保存更改？'}).getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('status')).toContainText('文件已被其他应用修改');expect(await page.evaluate(()=>window.__facet.getDocument().id)).toBe(id)
 await page.getByRole('dialog',{name:'保存更改？'}).getByRole('button',{name:'取消',exact:true}).click();await page.evaluate(()=>(window as any).testClose());await page.getByRole('dialog',{name:'保存更改？'}).getByRole('button',{name:'取消',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).testFileState.cancelled)).toBe(true);expect(await page.evaluate(()=>(window as any).testFileState.closed)).toBeUndefined()
})

test('pasted headings retain numbering and contents options; WebP exports as PNG for LaTeX',async({page})=>{
 const result=await page.evaluate(async()=>{const f=window.__facet,d=structuredClone(f.getDocument());d.content=[{type:'heading',attrs:{id:crypto.randomUUID(),level:2,toc:false,numbered:false},content:[{type:'text',text:'Heading'}]}];f.load(d);const node=f.editor.state.doc.firstChild.firstChild,{dom}=f.editor.view.serializeForClipboard(f.editor.state.doc.slice(1,1+node.nodeSize));d.content=[{type:'paragraph',attrs:{id:crypto.randomUUID()}}];f.load(d);f.editor.view.pasteHTML(dom.innerHTML);const heading=f.getDocument().content.find((n:any)=>n.type==='heading');const canvas=document.createElement('canvas');canvas.width=2;canvas.height=2;d.assets={webp:{name:'figure.webp',mime:'image/webp',data:canvas.toDataURL('image/webp').split(',')[1]}};d.content=[{type:'image',attrs:{id:crypto.randomUUID(),assetId:'webp'}}];const path='/src/core/latex.ts';const {latexArchive}=await import(/* @vite-ignore */path);const zipPath='/node_modules/.vite/deps/jszip.js';const {default:JSZip}=await import(/* @vite-ignore */zipPath);const zip=await JSZip.loadAsync(await latexArchive(d));return {toc:heading.attrs.toc,numbered:heading.attrs.numbered,png:!!zip.file('assets/webp.png'),source:d.assets.webp.mime}})
 expect(result).toEqual({toc:false,numbered:false,png:true,source:'image/webp'})
})
