import {chromium} from '@playwright/test'
import {writeFile,mkdir} from 'node:fs/promises'
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
const page=await browser.newPage({viewport:{width:1460,height:1000}})
page.on('pageerror',e=>console.log('PAGE ERROR',e.message))
await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.__facet?.editor);await page.evaluate(()=>document.fonts.ready)
await page.evaluate(()=>{
 const f=window.__facet,d=structuredClone(f.getDocument()),p=text=>({type:'paragraph',attrs:{id:crypto.randomUUID()},content:[{type:'text',text}]})
 d.content.push({type:'heading',attrs:{id:crypto.randomUUID(),level:1,numbered:true,toc:true},content:[{type:'text',text:'跨页验收'}]})
 d.content.push({type:'callout',attrs:{id:crypto.randomUUID(),variant:'important',title:'连续的长卡片',icon:'exclamation-circle',color:'harvardcrimson'},content:Array.from({length:15},(_,i)=>p(`段落 ${i+1} — Important finding. `+'内容应连续跨页，文字与边框不被裁切。'.repeat(8)))})
 d.content.push({type:'codeBlock',attrs:{id:crypto.randomUUID(),language:'python'},content:[{type:'text',text:Array.from({length:60},(_,i)=>`# 第 ${i+1} 行：中文代码验证\nprint("Facet ${i+1}")`).join('\n')}]})
 d.content.push({type:'table',attrs:{id:crypto.randomUUID()},content:Array.from({length:45},(_,i)=>({type:'tableRow',attrs:{id:crypto.randomUUID()},content:Array.from({length:3},(_,j)=>({type:i===0?'tableHeader':'tableCell',attrs:{id:crypto.randomUUID()},content:[p(i===0?['序号','说明','状态'][j]:[String(i),'跨页表格样例','完成'][j])]}))}))})
 d.content.push(p('END OF DOCUMENT — 验收终点'));f.load(d)
})
await page.waitForTimeout(500)
const count=await page.locator('.facet-page').count()
const expected=await page.locator('.facet-page').evaluateAll(pages=>pages.map(page=>({text:page.textContent,blocks:Array.from(page.querySelector('.page-content').children).map(e=>({id:e.getAttribute('data-id'),top:(e.getBoundingClientRect().top-page.getBoundingClientRect().top)/(page.getBoundingClientRect().width/793.7),height:e.getBoundingClientRect().height/(page.getBoundingClientRect().width/793.7)}))})))
const html=await page.evaluate(()=>window.__facet.exportHTML())
await mkdir('test-results',{recursive:true});await writeFile('test-results/pagination.html',html);await writeFile('test-results/layout.json',JSON.stringify({count,expected},null,2))
const print=await browser.newPage({viewport:{width:794,height:1123}});await print.setContent(html);await print.evaluate(()=>document.fonts.ready)
await print.pdf({path:'test-results/pagination.pdf',preferCSSPageSize:true,printBackground:true,margin:{top:0,bottom:0,left:0,right:0}})
await print.locator('.facet-page').first().screenshot({path:'test-results/pdf-source-page1.png'})
console.log(JSON.stringify({pages:count,issues:await page.evaluate(()=>window.__facet.getLayout().issues),snapshotPages:await print.locator('.facet-page').count()}))
await browser.close()
